name: "bam_trim_primers_ivar"
description: Trim primers using IVAR tools and perform summary statistics.
keywords:
  - amplicon sequencing
  - trimming
  - ivar
  - fasta
  - sort
  - bam
  - sam
  - cram

modules:
  - ivar/trim
  - samtools/sort
  - samtools/index
  - samtools/stats
  - samtools/idxstats
  - samtools/flagstat

tools:
  - ivar:
      description: |
        iVar - a computational package that contains functions broadly useful for viral amplicon-based sequencing.
      homepage: https://github.com/andersen-lab/ivar
      documentation: https://andersen-lab.github.io/ivar/html/manualpage.html
      licence: ["GPL-3.0-or-later"]

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - bam:
      type: file
      description: BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - bai:
      type: file
      description: Index file for co-ordinate sorted BAM file
      pattern: "*.bai"
  - fasta:
      type: file
      description: Reference genome fasta file
      pattern: "*.{fasta,fa}"
  - bed:
      type: file
      description: BED file with primer labels and positions
      pattern: "*.bed"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam_org:
      type: file
      description: iVar generated trimmed bam file (unsorted)
      pattern: "*.bam"
  - log_out:
      type: file
      description: Log file generated by iVar for use with MultiQC
      pattern: "*.log"
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - bai:
      type: file
      description: BAM/CRAM/SAM index file
      pattern: "*.{bai,crai,sai}"
  - crai:
      type: file
      description: BAM/CRAM/SAM index file
      pattern: "*.{bai,crai,sai}"
  - stats:
      type: file
      description: File containing samtools stats output
      pattern: "*.{stats}"
  - flagstat:
      type: file
      description: File containing samtools flagstat output
      pattern: "*.{flagstat}"
  - idxstats:
      type: file
      description: File containing samtools idxstats output
      pattern: "*.{idxstats}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@Joon-Klaps"
