name: "bam_trim_primers_ivar"
description: Trim primers using IVAR tools and perform summary statistics.
keywords:
  - amplicon sequencing
  - trimming
  - ivar
  - fasta
  - sort
  - bam
  - sam
  - cram

modules:
  - ivar/trim
  - samtools/sort
  - samtools/index
  - samtools/stats
  - samtools/idxstats
  - samtools/flagstat

tools:
  - ivar:
      description: |
        iVar - a computational package that contains functions broadly useful for viral amplicon-based sequencing.
      homepage: https://github.com/andersen-lab/ivar
      documentation: https://andersen-lab.github.io/ivar/html/manualpage.html
      licence: ["GPL-3.0-or-later"]

input:
  - ch_bam:
      type: file
      description: |
        Structure: [ val(meta), path(bam), path(bai) ]
        Groovy Map containing sample information
        e.g. [ id:'test' ], BAM/CRAM/SAM file, index file for co-ordinate sorted BAM file
  - ch_bed:
      type: file
      description: |
        Structure: path(bed)
        BED file with primer labels and positions
      pattern: "*.bed"
  - ch_fasta:
      type: file
      description: |
        Structure: path(fasta)
        Reference genome fasta file
      pattern: "*.{fasta,fa}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam_org:
      type: file
      description: |
        Structure: [ val(meta), path(bam) ]
        iVar generated trimmed bam file (unsorted)
  - log_out:
      type: file
      description: |
        Structure: [ val(meta), path(log) ]
        Log file generated by iVar for use with MultiQC
      pattern: "*.log"

  - bam:
      type: file
      description: |
        Structure: [ val(meta), path(bam) ]
        Sorted BAM/CRAM/SAM file
  - bai:
      type: file
      description: |
        Structure: [ val(meta), path(bai) ]
        BAM/CRAM/SAM index file
  - crai:
      type: file
      description: |
        Structure: [ val(meta), path(crai) ]
        BAM/CRAM/SAM index file
  - stats:
      type: file
      description: |
        Structure: [ val(meta), path(stats) ]
        File containing samtools stats output
  - flagstat:
      type: file
      description: |
        Structure: [ val(meta), path(flagstat) ]
        File containing samtools flagstat output
  - idxstats:
      type: file
      description: |
        Structure: [ val(meta), path(idxstats) ]
        File containing samtools idxstats output
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@Joon-Klaps"
