name: "bam_variant_demix_boot_freyja"
description: Recover relative lineage abundances from mixed SARS-CoV-2 samples from a sequencing dataset (BAM aligned to the Hu-1 reference)
keywords:
  - bam
  - variants
  - cram

modules:
  - freyja/variants
  - freyja/demix
  - freyja/update
  - freyja/boot

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - bam:
      type: file
      description: Sorted BAM file
      pattern: "*.bam"
  - fasta:
      type: file
      description: The reference sequence used for mapping and generating the BAM file
      pattern: "*.fa"
  - repeats:
      type: value (int)
      description: Number of bootstrap repeats to perform
  - lineage_meta:
      type: file
      description: File containing lineage metadata that correspond to barcodes
      pattern: "*lineages.json"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - variants:
      type: file
      description: File containing identified variants in a gff-like format
      pattern: "*.variants.tsv"
  - depths:
      type: file
      description: File containing depth of the variants
      pattern: "*.depth.tsv"
  - demix:
      type: file
      description: a tsv file that includes the lineages present, their corresponding abundances, and summarization by constellation
      pattern: "*.demix.tsv"
  - lineages:
      type: file
      description: a csv file that includes the lineages present and their corresponding abundances
      pattern: "*.lineages.csv"
  - summarized:
      type: file
      description: a csv file that includes the lineages present but summarized by constellation and their corresponding abundances
      pattern: "*.summarized.csv"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@Joon-Klaps"
