# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "fasta_creatdb_cluster_createtsv_mmseqs"
description: Cluster a fasta or fastq file using the MMseqs2 modules createdb, cluster and createtsv
keywords:
  - protein sequence
  - databases
  - clustering
  - searching
  - indexing
  - mmseqs2
  - tsv
modules:
  - mmseqs/createdb
  - mmseqs/cluster
  - mmseqs/createtsv
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - sequence:
      type: file
      description: Input sequences in FASTA/Q format to be indexed, clustered and converted to a summarising tsv
      pattern: "*.{fasta,fa,fna,fastq,fq}"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test' ]
  - bam:
      type: file
      description: Sorted BAM/CRAM/SAM file
      pattern: "*.{bam,cram,sam}"
  - bai:
      type: file
      description: BAM/CRAM/SAM samtools index
      pattern: "*.{bai,crai,sai}"
  - csi:
      type: file
      description: CSI samtools index
      pattern: "*.csi"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@Joon-Klaps"
